/**
 * Demo catalogue for Meridian.
 * Prices are in INR. Brands are used for demonstration only.
 */

export const categories = [
  {
    name: 'Electronics',
    tagline: 'Phones, audio & computing',
    description: 'Flagship phones, laptops, audio gear and everyday accessories from brands you trust.',
    icon: 'laptop',
    accent: 'indigo',
    order: 1,
  },
  {
    name: 'Fashion',
    tagline: 'Apparel, footwear & bags',
    description: 'Considered essentials and seasonal drops — menswear, womenswear, shoes and carry goods.',
    icon: 'shirt',
    accent: 'rose',
    order: 2,
  },
  {
    name: 'Home & Living',
    tagline: 'Kitchen, decor & comfort',
    description: 'Everything that makes a house feel like home — kitchen, bedding, lighting and storage.',
    icon: 'sofa',
    accent: 'amber',
    order: 3,
  },
  {
    name: 'Beauty & Care',
    tagline: 'Skincare, hair & fragrance',
    description: 'Clean formulations, dermat-tested skincare and everyday grooming, curated by category.',
    icon: 'sparkles',
    accent: 'pink',
    order: 4,
  },
  {
    name: 'Sports & Outdoors',
    tagline: 'Fitness, cycling & travel',
    description: 'Training gear, cycle accessories and camp-ready equipment built for Indian weather.',
    icon: 'dumbbell',
    accent: 'emerald',
    order: 5,
  },
  {
    name: 'Books & Stationery',
    tagline: 'Read, write, organise',
    description: 'Bestsellers, reference titles and desk essentials that make the workday calmer.',
    icon: 'book',
    accent: 'teal',
    order: 6,
  },
];

export const products = [
  /* ---------------------------- ELECTRONICS ---------------------------- */
  {
    name: 'Aurex Air 5 Wireless Earbuds',
    brand: 'Aurex',
    category: 'Electronics',
    price: 2499,
    compareAtPrice: 4999,
    stock: 64,
    rating: { average: 4.4, count: 1284 },
    sold: 3120,
    tags: ['audio', 'earbuds', 'anc', 'bluetooth'],
    description:
      'Hybrid active noise cancellation, 42 hours of total playtime and a 10 mm dynamic driver tuned for Indian listening habits. IPX5 rated for monsoon commutes.',
    highlights: ['42 hr battery with case', 'Hybrid ANC up to 35 dB', 'Bluetooth 5.3 with low-latency game mode'],
    specs: [
      { key: 'Driver', value: '10 mm dynamic' },
      { key: 'Battery', value: '8 hr buds / 42 hr case' },
      { key: 'Water resistance', value: 'IPX5' },
    ],
    colors: [
      { name: 'Midnight', hex: '#111827' },
      { name: 'Sand', hex: '#D8C7AE' },
    ],
    featured: true,
  },
  {
    name: 'Nordbook 14 Ultrabook (16 GB / 512 GB)',
    brand: 'Nord',
    category: 'Electronics',
    price: 62990,
    compareAtPrice: 74990,
    stock: 12,
    rating: { average: 4.6, count: 412 },
    sold: 268,
    tags: ['laptop', 'ultrabook', 'work'],
    description:
      'A 1.28 kg magnesium-alloy ultrabook with a 14-inch 2.8K OLED panel, 12-hour real-world battery and a backlit keyboard tuned for long writing sessions.',
    highlights: ['14" 2.8K OLED, 90 Hz', '1.28 kg magnesium body', '12 hr battery, 65 W USB-C charging'],
    specs: [
      { key: 'Display', value: '14" 2.8K OLED 90 Hz' },
      { key: 'Memory', value: '16 GB LPDDR5' },
      { key: 'Storage', value: '512 GB NVMe SSD' },
    ],
    colors: [{ name: 'Graphite', hex: '#3F3F46' }],
    featured: true,
  },
  {
    name: 'Lumio Smart Watch S2 (AMOLED)',
    brand: 'Lumio',
    category: 'Electronics',
    price: 3799,
    compareAtPrice: 6999,
    stock: 88,
    rating: { average: 4.2, count: 2210 },
    sold: 5410,
    tags: ['wearable', 'watch', 'fitness'],
    description:
      '1.43-inch AMOLED display, 120 sport modes, SpO₂ and sleep tracking with a 14-day battery. Comes with two interchangeable straps.',
    highlights: ['14-day battery life', '120 sport modes', 'IP68 water resistant'],
    specs: [
      { key: 'Display', value: '1.43" AMOLED' },
      { key: 'Battery', value: 'Up to 14 days' },
      { key: 'Sensors', value: 'HR, SpO₂, accelerometer' },
    ],
    colors: [
      { name: 'Black', hex: '#0F172A' },
      { name: 'Olive', hex: '#5C6B4F' },
    ],
    featured: true,
  },
  {
    name: 'Voltcore 20K Power Bank (33 W)',
    brand: 'Voltcore',
    category: 'Electronics',
    price: 1899,
    compareAtPrice: 2999,
    stock: 140,
    rating: { average: 4.5, count: 3890 },
    sold: 9200,
    tags: ['powerbank', 'charging', 'travel'],
    description:
      'BIS-certified 20,000 mAh cell with 33 W USB-C fast charge, a digital percentage readout and pass-through charging for two devices at once.',
    highlights: ['33 W USB-C fast charge', 'Digital % display', 'BIS certified cell'],
    specs: [
      { key: 'Capacity', value: '20,000 mAh' },
      { key: 'Output', value: '33 W USB-C / 18 W USB-A' },
      { key: 'Recharge time', value: '4.5 hours' },
    ],
    colors: [{ name: 'Charcoal', hex: '#27272A' }],
  },
  {
    name: 'Sonor Studio Monitor Headphones',
    brand: 'Sonor',
    category: 'Electronics',
    price: 6499,
    compareAtPrice: 8999,
    stock: 26,
    rating: { average: 4.7, count: 508 },
    sold: 740,
    tags: ['audio', 'headphones', 'studio'],
    description:
      'Closed-back 45 mm drivers with a flat reference tuning, memory-foam earcups and a detachable cable. Built for mixing, podcasts and long study sessions.',
    highlights: ['Flat reference tuning', 'Memory-foam earcups', 'Detachable 3 m cable'],
    specs: [
      { key: 'Driver', value: '45 mm dynamic' },
      { key: 'Impedance', value: '32 Ω' },
      { key: 'Weight', value: '285 g' },
    ],
    colors: [{ name: 'Walnut', hex: '#6B4A2F' }],
  },
  {
    name: 'Pixelview 1080p Webcam with Ring Light',
    brand: 'Pixelview',
    category: 'Electronics',
    price: 2299,
    compareAtPrice: 3499,
    stock: 47,
    rating: { average: 4.1, count: 932 },
    sold: 1420,
    tags: ['webcam', 'work', 'streaming'],
    description:
      '1080p/30fps sensor with autofocus, dual noise-cancelling mics and a built-in 3-temperature ring light for calls in low light.',
    highlights: ['1080p autofocus', 'Built-in ring light', 'Dual noise-cancelling mics'],
    specs: [
      { key: 'Resolution', value: '1920 × 1080 @ 30 fps' },
      { key: 'Field of view', value: '78°' },
      { key: 'Mount', value: 'Clip + tripod thread' },
    ],
    colors: [{ name: 'Black', hex: '#111827' }],
  },
  {
    name: 'Keeb One Mechanical Keyboard (75%)',
    brand: 'Keeb',
    category: 'Electronics',
    price: 4999,
    compareAtPrice: 6499,
    stock: 33,
    rating: { average: 4.6, count: 611 },
    sold: 890,
    tags: ['keyboard', 'mechanical', 'desk'],
    description:
      'Gasket-mounted 75% layout with hot-swappable linear switches, doubleshot PBT keycaps and three connectivity modes — USB-C, 2.4 GHz and Bluetooth.',
    highlights: ['Hot-swap switches', 'Doubleshot PBT keycaps', 'USB-C / 2.4 GHz / Bluetooth'],
    specs: [
      { key: 'Layout', value: '75% (82 keys)' },
      { key: 'Switches', value: 'Linear, hot-swappable' },
      { key: 'Battery', value: '4000 mAh' },
    ],
    colors: [
      { name: 'Bone', hex: '#EDE7DA' },
      { name: 'Ink', hex: '#1F2937' },
    ],
  },

  /* ------------------------------ FASHION ------------------------------ */
  {
    name: 'Everyday Oxford Shirt — Sea Green',
    brand: 'Threadform',
    category: 'Fashion',
    price: 1299,
    compareAtPrice: 2199,
    stock: 72,
    rating: { average: 4.3, count: 1560 },
    sold: 3400,
    tags: ['shirt', 'menswear', 'formal', 'cotton'],
    description:
      'Breathable 60-count combed cotton with a soft-touch finish, mother-of-pearl buttons and a slim-but-not-tight cut that works for office and dinner.',
    highlights: ['60-count combed cotton', 'Slim regular fit', 'Wrinkle-resistant finish'],
    specs: [
      { key: 'Fabric', value: '100% combed cotton' },
      { key: 'Fit', value: 'Slim' },
      { key: 'Care', value: 'Machine wash cold' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Sea Green', hex: '#2F6B5B' },
      { name: 'Sky', hex: '#7FA8C9' },
      { name: 'White', hex: '#F5F5F4' },
    ],
    featured: true,
  },
  {
    name: 'Terra Runner Sneakers',
    brand: 'Stride',
    category: 'Fashion',
    price: 3499,
    compareAtPrice: 5499,
    stock: 54,
    rating: { average: 4.5, count: 2044 },
    sold: 4180,
    tags: ['shoes', 'sneakers', 'running'],
    description:
      'Knit upper with a responsive EVA midsole and a rubber outsole tested for 500 km. Lightweight enough for a morning run, clean enough for errands.',
    highlights: ['220 g per shoe', 'Responsive EVA midsole', 'Anti-slip rubber outsole'],
    specs: [
      { key: 'Upper', value: 'Engineered knit' },
      { key: 'Drop', value: '8 mm' },
      { key: 'Weight', value: '220 g (UK 8)' },
    ],
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: [
      { name: 'Ash', hex: '#9CA3AF' },
      { name: 'Terracotta', hex: '#B4654A' },
    ],
    featured: true,
  },
  {
    name: 'Canvas Weekender Duffel (35 L)',
    brand: 'Wayfare',
    category: 'Fashion',
    price: 2799,
    compareAtPrice: 4299,
    stock: 31,
    rating: { average: 4.4, count: 486 },
    sold: 690,
    tags: ['bags', 'travel', 'duffel'],
    description:
      'Waxed 16 oz canvas with leather trim, a padded laptop sleeve and a separate shoe compartment. Cabin-friendly for a two-day trip.',
    highlights: ['Padded 15.6" laptop sleeve', 'Shoe compartment', 'Cabin-friendly 35 L'],
    specs: [
      { key: 'Material', value: '16 oz waxed canvas + leather' },
      { key: 'Capacity', value: '35 litres' },
      { key: 'Warranty', value: '2 years' },
    ],
    colors: [{ name: 'Olive', hex: '#5A6445' }],
  },
  {
    name: 'Linen Blend Kurta — Indigo',
    brand: 'Threadform',
    category: 'Fashion',
    price: 1899,
    compareAtPrice: 2999,
    stock: 46,
    rating: { average: 4.6, count: 733 },
    sold: 1120,
    tags: ['kurta', 'ethnic', 'linen'],
    description:
      'A relaxed linen-cotton kurta with a mandarin collar and side pockets. Breathable through a Delhi summer and sharp enough for a family function.',
    highlights: ['Linen-cotton blend', 'Mandarin collar', 'Two side pockets'],
    specs: [
      { key: 'Fabric', value: '55% linen, 45% cotton' },
      { key: 'Fit', value: 'Relaxed' },
      { key: 'Length', value: 'Knee length' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Indigo', hex: '#33456B' },
      { name: 'Ivory', hex: '#EFE9DC' },
    ],
  },
  {
    name: 'Merino Crew Sweater',
    brand: 'Northvale',
    category: 'Fashion',
    price: 3299,
    compareAtPrice: 4999,
    stock: 38,
    rating: { average: 4.5, count: 398 },
    sold: 520,
    tags: ['sweater', 'winter', 'merino'],
    description:
      'Extra-fine 19.5 micron merino that regulates temperature without bulk. Ribbed cuffs hold their shape after a season of wear.',
    highlights: ['19.5 micron merino', 'Temperature regulating', 'Anti-pilling knit'],
    specs: [
      { key: 'Fabric', value: '100% merino wool' },
      { key: 'Gauge', value: '12 GG' },
      { key: 'Care', value: 'Hand wash cold' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Camel', hex: '#B08A5A' },
      { name: 'Slate', hex: '#4B5563' },
    ],
  },
  {
    name: 'Minimalist Leather Watch',
    brand: 'Hourmark',
    category: 'Fashion',
    price: 4499,
    compareAtPrice: 7999,
    stock: 22,
    rating: { average: 4.7, count: 861 },
    sold: 1010,
    tags: ['watch', 'accessories', 'leather'],
    description:
      'A 38 mm steel case with a sapphire-coated crystal and a genuine leather strap. Japanese quartz movement with a 3-year battery.',
    highlights: ['Sapphire-coated crystal', 'Japanese quartz movement', 'Interchangeable strap'],
    specs: [
      { key: 'Case', value: '38 mm stainless steel' },
      { key: 'Water resistance', value: '5 ATM' },
      { key: 'Warranty', value: '2 years' },
    ],
    colors: [
      { name: 'Tan', hex: '#A9743F' },
      { name: 'Black', hex: '#1C1917' },
    ],
    featured: true,
  },
  {
    name: 'High-Rise Straight Leg Jeans',
    brand: 'Denim Co.',
    category: 'Fashion',
    price: 2199,
    compareAtPrice: 3299,
    stock: 65,
    rating: { average: 4.2, count: 1780 },
    sold: 3900,
    tags: ['jeans', 'womenswear', 'denim'],
    description:
      'Rigid 12.5 oz denim with 2% stretch, a flattering high rise and a straight leg that breaks cleanly over a sneaker.',
    highlights: ['12.5 oz denim', 'High rise, straight leg', 'Fade-resistant indigo'],
    specs: [
      { key: 'Fabric', value: '98% cotton, 2% elastane' },
      { key: 'Rise', value: 'High' },
      { key: 'Inseam', value: '30"' },
    ],
    sizes: ['26', '28', '30', '32', '34'],
    colors: [
      { name: 'Mid Blue', hex: '#4A6B8A' },
      { name: 'Washed Black', hex: '#2A2A2E' },
    ],
  },

  /* --------------------------- HOME & LIVING --------------------------- */
  {
    name: 'Ceramic Non-Stick Cookware Set (5 pc)',
    brand: 'Hearth',
    category: 'Home & Living',
    price: 5499,
    compareAtPrice: 8999,
    stock: 29,
    rating: { average: 4.4, count: 1102 },
    sold: 1640,
    tags: ['kitchen', 'cookware', 'nonstick'],
    description:
      'PFOA-free ceramic coating on forged aluminium bodies — kadhai, tawa, saucepan and two frying pans. Induction compatible and dishwasher safe.',
    highlights: ['PFOA-free ceramic coating', 'Induction compatible', 'Stay-cool bakelite handles'],
    specs: [
      { key: 'Pieces', value: '5' },
      { key: 'Body', value: 'Forged aluminium, 3.5 mm' },
      { key: 'Warranty', value: '2 years' },
    ],
    colors: [{ name: 'Cream', hex: '#E8DFCE' }],
    featured: true,
  },
  {
    name: 'Egyptian Cotton Bedsheet Set (King)',
    brand: 'Slumber',
    category: 'Home & Living',
    price: 2299,
    compareAtPrice: 3999,
    stock: 58,
    rating: { average: 4.6, count: 2318 },
    sold: 4300,
    tags: ['bedding', 'bedsheet', 'cotton'],
    description:
      '400 thread-count long-staple cotton with a sateen weave that stays cool through the night. Includes two pillow covers.',
    highlights: ['400 TC long-staple cotton', 'Sateen weave', 'Fits up to 8" mattress'],
    specs: [
      { key: 'Size', value: '108 × 108 inches' },
      { key: 'Thread count', value: '400 TC' },
      { key: 'Includes', value: '2 pillow covers' },
    ],
    colors: [
      { name: 'Sandstone', hex: '#DCC9AE' },
      { name: 'Sage', hex: '#9CAE9B' },
    ],
  },
  {
    name: 'Arc Floor Lamp — Warm Dimmable',
    brand: 'Lume',
    category: 'Home & Living',
    price: 4299,
    compareAtPrice: 6499,
    stock: 18,
    rating: { average: 4.3, count: 312 },
    sold: 410,
    tags: ['lighting', 'lamp', 'decor'],
    description:
      'A brushed-brass arc with a linen drum shade and a foot dimmer that sweeps from 2200 K candlelight to a warm 3000 K reading glow.',
    highlights: ['Stepless foot dimmer', '2200–3000 K warm light', 'Marble-weighted base'],
    specs: [
      { key: 'Height', value: '185 cm' },
      { key: 'Bulb', value: 'E27, 9 W LED included' },
      { key: 'Finish', value: 'Brushed brass' },
    ],
    colors: [{ name: 'Brass', hex: '#B08D57' }],
    featured: true,
  },
  {
    name: 'Ergonomic Mesh Office Chair',
    brand: 'Postur',
    category: 'Home & Living',
    price: 12999,
    compareAtPrice: 18999,
    stock: 14,
    rating: { average: 4.5, count: 894 },
    sold: 1180,
    tags: ['furniture', 'chair', 'work'],
    description:
      'Breathable mesh back with adjustable lumbar support, 4D armrests and a class-4 gas lift rated for 8-hour workdays.',
    highlights: ['Adjustable lumbar support', '4D armrests', 'Class-4 gas lift, 120 kg rated'],
    specs: [
      { key: 'Back', value: 'Breathable mesh' },
      { key: 'Load capacity', value: '120 kg' },
      { key: 'Warranty', value: '3 years' },
    ],
    colors: [{ name: 'Graphite', hex: '#333333' }],
  },
  {
    name: 'Stoneware Dinner Set (18 pc)',
    brand: 'Hearth',
    category: 'Home & Living',
    price: 3499,
    compareAtPrice: 5499,
    stock: 41,
    rating: { average: 4.4, count: 640 },
    sold: 880,
    tags: ['kitchen', 'dinnerware', 'ceramic'],
    description:
      'Reactive-glazed stoneware for six — chip-resistant, microwave safe and finished so no two plates are exactly alike.',
    highlights: ['Service for 6', 'Chip-resistant glaze', 'Microwave & dishwasher safe'],
    specs: [
      { key: 'Pieces', value: '18' },
      { key: 'Material', value: 'High-fired stoneware' },
      { key: 'Finish', value: 'Reactive glaze' },
    ],
    colors: [{ name: 'Clay', hex: '#C8A48D' }],
  },
  {
    name: 'Bamboo Desk Organiser with Drawer',
    brand: 'Tidy',
    category: 'Home & Living',
    price: 1199,
    compareAtPrice: 1899,
    stock: 96,
    rating: { average: 4.2, count: 421 },
    sold: 1320,
    tags: ['desk', 'storage', 'organiser'],
    description:
      'Solid bamboo with a felt-lined drawer, phone stand and cable notch — clears a desk in about ninety seconds.',
    highlights: ['Solid bamboo build', 'Felt-lined drawer', 'Built-in phone stand'],
    specs: [
      { key: 'Dimensions', value: '32 × 22 × 12 cm' },
      { key: 'Material', value: 'Moso bamboo' },
      { key: 'Finish', value: 'Food-safe lacquer' },
    ],
    colors: [{ name: 'Natural', hex: '#C9A97B' }],
  },
  {
    name: 'Scented Soy Candle Trio',
    brand: 'Ember',
    category: 'Home & Living',
    price: 899,
    compareAtPrice: 1499,
    stock: 120,
    rating: { average: 4.6, count: 1502 },
    sold: 3600,
    tags: ['decor', 'candle', 'fragrance'],
    description:
      'Three 120 g soy candles — Vetiver & Smoke, Cardamom Chai and Sea Salt — with 30-hour burn times and reusable amber glass.',
    highlights: ['30 hr burn each', '100% soy wax', 'Reusable amber glass'],
    specs: [
      { key: 'Set', value: '3 × 120 g' },
      { key: 'Wax', value: 'Natural soy' },
      { key: 'Wick', value: 'Cotton, lead-free' },
    ],
    colors: [{ name: 'Amber', hex: '#B4762E' }],
  },

  /* --------------------------- BEAUTY & CARE --------------------------- */
  {
    name: '10% Niacinamide Face Serum (30 ml)',
    brand: 'Dermaleaf',
    category: 'Beauty & Care',
    price: 649,
    compareAtPrice: 999,
    stock: 210,
    rating: { average: 4.5, count: 4820 },
    sold: 12400,
    tags: ['skincare', 'serum', 'niacinamide'],
    description:
      'A lightweight 10% niacinamide serum with zinc PCA that visibly reduces oiliness and post-acne marks. Dermatologically tested, fragrance free.',
    highlights: ['10% niacinamide + 1% zinc', 'Fragrance free', 'Non-comedogenic'],
    specs: [
      { key: 'Volume', value: '30 ml' },
      { key: 'Skin type', value: 'Oily / combination' },
      { key: 'Use', value: 'AM & PM' },
    ],
    featured: true,
  },
  {
    name: 'Vitamin C Brightening Cream (50 g)',
    brand: 'Dermaleaf',
    category: 'Beauty & Care',
    price: 899,
    compareAtPrice: 1399,
    stock: 145,
    rating: { average: 4.3, count: 2140 },
    sold: 5200,
    tags: ['skincare', 'moisturiser', 'vitamin-c'],
    description:
      'Stabilised 15% ethyl ascorbic acid in a non-greasy base with hyaluronic acid — brightens tone without the sticky finish.',
    highlights: ['15% stabilised vitamin C', 'With hyaluronic acid', 'Non-greasy finish'],
    specs: [
      { key: 'Volume', value: '50 g' },
      { key: 'Skin type', value: 'All' },
      { key: 'Use', value: 'AM before sunscreen' },
    ],
  },
  {
    name: 'Argan Oil Repair Hair Mask (250 g)',
    brand: 'Keratin Lab',
    category: 'Beauty & Care',
    price: 749,
    compareAtPrice: 1199,
    stock: 88,
    rating: { average: 4.4, count: 1330 },
    sold: 2900,
    tags: ['haircare', 'mask', 'argan'],
    description:
      'A five-minute deep-conditioning mask with cold-pressed argan oil and hydrolysed keratin for chemically treated or heat-styled hair.',
    highlights: ['Cold-pressed argan oil', '5-minute treatment', 'Sulphate & paraben free'],
    specs: [
      { key: 'Volume', value: '250 g' },
      { key: 'Hair type', value: 'Dry / damaged' },
      { key: 'Use', value: 'Twice a week' },
    ],
  },
  {
    name: 'SPF 50 PA++++ Matte Sunscreen (50 g)',
    brand: 'Solguard',
    category: 'Beauty & Care',
    price: 599,
    compareAtPrice: 899,
    stock: 176,
    rating: { average: 4.6, count: 5610 },
    sold: 14800,
    tags: ['skincare', 'sunscreen', 'spf'],
    description:
      'Broad-spectrum SPF 50 PA++++ in a water-light gel that leaves no white cast on deeper skin tones. Fragrance free and safe under makeup.',
    highlights: ['Broad spectrum SPF 50', 'No white cast', 'Water-light gel texture'],
    specs: [
      { key: 'Volume', value: '50 g' },
      { key: 'Protection', value: 'SPF 50, PA++++' },
      { key: 'Texture', value: 'Gel-cream' },
    ],
    featured: true,
  },
  {
    name: 'Beard Grooming Kit (4 pc)',
    brand: 'Barber & Co.',
    category: 'Beauty & Care',
    price: 1299,
    compareAtPrice: 1999,
    stock: 62,
    rating: { average: 4.2, count: 720 },
    sold: 1140,
    tags: ['grooming', 'mens', 'beard'],
    description:
      'Beard oil, balm, wooden comb and scissors in a canvas roll — everything for a clean shape-up between barber visits.',
    highlights: ['4-piece kit', 'Cold-pressed oils', 'Canvas travel roll'],
    specs: [
      { key: 'Pieces', value: '4' },
      { key: 'Fragrance', value: 'Cedar & bergamot' },
      { key: 'Packaging', value: 'Canvas roll' },
    ],
  },
  {
    name: 'Electric Facial Cleansing Brush',
    brand: 'Glowform',
    category: 'Beauty & Care',
    price: 1899,
    compareAtPrice: 2999,
    stock: 44,
    rating: { average: 4.1, count: 512 },
    sold: 830,
    tags: ['skincare', 'device', 'cleansing'],
    description:
      'Soft silicone bristles with five vibration intensities, a 90-day battery and full IPX7 waterproofing for use in the shower.',
    highlights: ['5 intensity levels', '90-day battery', 'IPX7 waterproof'],
    specs: [
      { key: 'Bristles', value: 'Medical-grade silicone' },
      { key: 'Battery', value: 'USB-C, 90 days' },
      { key: 'Waterproof', value: 'IPX7' },
    ],
    colors: [{ name: 'Blush', hex: '#E8B4B8' }],
  },
  {
    name: 'Hydrating Lip & Hand Care Set',
    brand: 'Ember',
    category: 'Beauty & Care',
    price: 699,
    compareAtPrice: 1099,
    stock: 130,
    rating: { average: 4.3, count: 980 },
    sold: 2100,
    tags: ['gifting', 'handcare', 'lipcare'],
    description:
      'A shea-butter hand cream, tinted lip balm and cuticle oil in a gift box — the low-effort present that always lands.',
    highlights: ['Shea butter base', 'Gift-ready box', 'Tinted + clear balm'],
    specs: [
      { key: 'Pieces', value: '3' },
      { key: 'Volume', value: '50 g + 5 g + 10 ml' },
      { key: 'Fragrance', value: 'Vanilla & shea' },
    ],
  },

  /* -------------------------- SPORTS & OUTDOORS ------------------------- */
  {
    name: 'Adjustable Dumbbell Set (20 kg)',
    brand: 'Ironpath',
    category: 'Sports & Outdoors',
    price: 5999,
    compareAtPrice: 8999,
    stock: 24,
    rating: { average: 4.5, count: 640 },
    sold: 890,
    tags: ['fitness', 'weights', 'home-gym'],
    description:
      'Two 10 kg plates, one 6 kg bar, connectors and a carry case — a full home setup that fits under a bed.',
    highlights: ['20 kg total', 'PVC-coated plates', 'Carry case included'],
    specs: [
      { key: 'Total weight', value: '20 kg' },
      { key: 'Bar', value: '14" steel, 6 kg' },
      { key: 'Plates', value: '4 × 2.5 kg, 4 × 1.25 kg' },
    ],
    featured: true,
  },
  {
    name: 'Pro Yoga Mat 6 mm (Anti-Slip)',
    brand: 'Ironpath',
    category: 'Sports & Outdoors',
    price: 1299,
    compareAtPrice: 1999,
    stock: 105,
    rating: { average: 4.6, count: 2410 },
    sold: 6300,
    tags: ['fitness', 'yoga', 'mat'],
    description:
      'Closed-cell TPE with an alignment grid, 6 mm cushioning for knees and a textured surface that grips even in a hot room.',
    highlights: ['6 mm cushioning', 'Alignment grid lines', 'Closed-cell, sweat resistant'],
    specs: [
      { key: 'Size', value: '183 × 61 cm' },
      { key: 'Thickness', value: '6 mm' },
      { key: 'Material', value: 'TPE, latex free' },
    ],
    colors: [
      { name: 'Forest', hex: '#2F5D50' },
      { name: 'Plum', hex: '#6B3A56' },
    ],
  },
  {
    name: 'All-Terrain Cycling Helmet (MIPS)',
    brand: 'Trailhead',
    category: 'Sports & Outdoors',
    price: 3299,
    compareAtPrice: 4999,
    stock: 37,
    rating: { average: 4.4, count: 388 },
    sold: 540,
    tags: ['cycling', 'helmet', 'safety'],
    description:
      'In-mould shell with 22 vents, a dial-fit retention system and a removable visor. IS17119 certified.',
    highlights: ['IS17119 certified', '22 air vents', 'Dial-fit adjustment'],
    specs: [
      { key: 'Weight', value: '290 g' },
      { key: 'Sizes', value: 'M (54–58 cm), L (58–62 cm)' },
      { key: 'Certification', value: 'IS17119' },
    ],
    sizes: ['M', 'L'],
    colors: [
      { name: 'Matte Black', hex: '#1A1A1A' },
      { name: 'Hi-Vis Yellow', hex: '#D9C22E' },
    ],
  },
  {
    name: 'Insulated Trekking Bottle (1 L)',
    brand: 'Trailhead',
    category: 'Sports & Outdoors',
    price: 1499,
    compareAtPrice: 2299,
    stock: 152,
    rating: { average: 4.7, count: 1820 },
    sold: 4400,
    tags: ['outdoor', 'bottle', 'travel'],
    description:
      'Double-wall vacuum steel keeps drinks cold for 24 hours or hot for 12, with a leak-proof lid that survives being thrown in a rucksack.',
    highlights: ['24 hr cold / 12 hr hot', '304 stainless steel', 'Leak-proof twist lid'],
    specs: [
      { key: 'Capacity', value: '1 litre' },
      { key: 'Material', value: '304 food-grade steel' },
      { key: 'Weight', value: '480 g' },
    ],
    colors: [
      { name: 'Steel', hex: '#B9BEC4' },
      { name: 'Rust', hex: '#A5573A' },
    ],
  },
  {
    name: 'Resistance Band Set (5 pc)',
    brand: 'Ironpath',
    category: 'Sports & Outdoors',
    price: 799,
    compareAtPrice: 1499,
    stock: 240,
    rating: { average: 4.3, count: 1140 },
    sold: 3800,
    tags: ['fitness', 'bands', 'home-gym'],
    description:
      'Five latex bands from 5 kg to 40 kg with door anchor, handles and ankle straps — 10 kg of resistance that weighs 800 g.',
    highlights: ['5–40 kg resistance range', 'Door anchor + handles', 'Mesh carry bag'],
    specs: [
      { key: 'Pieces', value: '5 bands + accessories' },
      { key: 'Material', value: 'Natural latex' },
      { key: 'Max load', value: '40 kg' },
    ],
  },
  {
    name: '4-Person Family Camping Tent',
    brand: 'Basecamp',
    category: 'Sports & Outdoors',
    price: 6499,
    compareAtPrice: 9999,
    stock: 16,
    rating: { average: 4.2, count: 274 },
    sold: 320,
    tags: ['camping', 'tent', 'outdoor'],
    description:
      'Freestanding two-room dome with a 3000 mm hydrostatic head, taped seams and a five-minute colour-coded setup.',
    highlights: ['3000 mm waterproof rating', 'Two rooms + vestibule', '5-minute setup'],
    specs: [
      { key: 'Capacity', value: '4 persons' },
      { key: 'Weight', value: '4.6 kg' },
      { key: 'Poles', value: 'Fibreglass, colour coded' },
    ],
    featured: true,
  },
  {
    name: 'Cork Yoga Block Pair',
    brand: 'Ironpath',
    category: 'Sports & Outdoors',
    price: 899,
    compareAtPrice: 1399,
    stock: 78,
    rating: { average: 4.5, count: 610 },
    sold: 1250,
    tags: ['yoga', 'accessories'],
    description:
      'High-density natural cork blocks with rounded edges — firmer and more stable than foam, and they last for years.',
    highlights: ['100% natural cork', 'Rounded edges', 'Sold as a pair'],
    specs: [
      { key: 'Dimensions', value: '23 × 15 × 10 cm' },
      { key: 'Weight', value: '780 g each' },
      { key: 'Quantity', value: '2' },
    ],
  },

  /* ------------------------- BOOKS & STATIONERY ------------------------- */
  {
    name: 'The Quiet Discipline (Paperback)',
    brand: 'Northwind Press',
    category: 'Books & Stationery',
    price: 349,
    compareAtPrice: 499,
    stock: 180,
    rating: { average: 4.6, count: 2980 },
    sold: 8600,
    tags: ['book', 'nonfiction', 'bestseller'],
    description:
      'A practical field guide to building habits that survive real life — 320 pages, no jargon, and a chapter structure you can finish in a week.',
    highlights: ['320 pages', 'Bestseller, 40+ weeks', 'Includes habit workbook'],
    specs: [
      { key: 'Format', value: 'Paperback' },
      { key: 'Pages', value: '320' },
      { key: 'Language', value: 'English' },
    ],
    featured: true,
  },
  {
    name: 'Fountain Pen Starter Set (Fine Nib)',
    brand: 'Inkwell',
    category: 'Books & Stationery',
    price: 1599,
    compareAtPrice: 2499,
    stock: 52,
    rating: { average: 4.7, count: 486 },
    sold: 760,
    tags: ['stationery', 'pen', 'writing'],
    description:
      'A brass-bodied fountain pen with an iridium fine nib, a piston converter and six ink cartridges. Writes smooth on cheap paper.',
    highlights: ['Iridium fine nib', 'Piston converter included', 'Brass body, 32 g'],
    specs: [
      { key: 'Nib', value: 'Fine (F), iridium tipped' },
      { key: 'Filling', value: 'Converter + cartridges' },
      { key: 'Body', value: 'Solid brass' },
    ],
    colors: [
      { name: 'Graphite', hex: '#2B2B2B' },
      { name: 'Forest', hex: '#274B3B' },
    ],
  },
  {
    name: 'Dot-Grid Notebook — A5 (Set of 3)',
    brand: 'Inkwell',
    category: 'Books & Stationery',
    price: 649,
    compareAtPrice: 999,
    stock: 220,
    rating: { average: 4.8, count: 1620 },
    sold: 5200,
    tags: ['stationery', 'notebook', 'journaling'],
    description:
      '120 gsm bleed-proof paper with a 5 mm dot grid, lay-flat binding and a numbered index — three notebooks in kraft, ink and moss.',
    highlights: ['120 gsm bleed-proof paper', 'Lay-flat binding', '180 pages each'],
    specs: [
      { key: 'Size', value: 'A5 (148 × 210 mm)' },
      { key: 'Paper', value: '120 gsm, 5 mm dots' },
      { key: 'Quantity', value: '3' },
    ],
    featured: true,
  },
  {
    name: 'Desk Study Lamp (USB-C, 3 Modes)',
    brand: 'Lume',
    category: 'Books & Stationery',
    price: 1799,
    compareAtPrice: 2799,
    stock: 67,
    rating: { average: 4.4, count: 890 },
    sold: 1440,
    tags: ['lighting', 'study', 'desk'],
    description:
      'Flicker-free LED with three colour temperatures, stepless brightness, a fold-flat hinge and USB-C power so it runs off a power bank.',
    highlights: ['Flicker-free LED', '3 colour temperatures', 'Folds flat for travel'],
    specs: [
      { key: 'Brightness', value: '450 lumens' },
      { key: 'Colour temp', value: '3000 / 4000 / 5000 K' },
      { key: 'Power', value: 'USB-C, 5 W' },
    ],
    colors: [{ name: 'White', hex: '#F1F1EF' }],
  },
  {
    name: 'Algorithms Decoded (Hardcover)',
    brand: 'Techlit',
    category: 'Books & Stationery',
    price: 899,
    compareAtPrice: 1299,
    stock: 44,
    rating: { average: 4.5, count: 720 },
    sold: 1180,
    tags: ['book', 'programming', 'cs'],
    description:
      'Interview-grade coverage of data structures and algorithms with 240 worked problems in Python and Java side by side.',
    highlights: ['240 worked problems', 'Python + Java solutions', 'Interview pattern index'],
    specs: [
      { key: 'Format', value: 'Hardcover' },
      { key: 'Pages', value: '612' },
      { key: 'Language', value: 'English' },
    ],
  },
  {
    name: 'Steel Geometry Box — 12 Pieces',
    brand: 'Inkwell',
    category: 'Books & Stationery',
    price: 449,
    compareAtPrice: 699,
    stock: 160,
    rating: { average: 4.2, count: 340 },
    sold: 620,
    tags: ['stationery', 'school', 'geometry'],
    description:
      'Stainless steel compass, protractor, set squares and divider in a fitted metal case — accurate enough for board exams.',
    highlights: ['12 stainless pieces', 'Precision compass', 'Fitted metal case'],
    specs: [
      { key: 'Pieces', value: '12' },
      { key: 'Material', value: 'Stainless steel' },
      { key: 'Case', value: 'Metal tin' },
    ],
  },
  {
    name: 'Weekly Planner & Habit Tracker 2026',
    brand: 'Inkwell',
    category: 'Books & Stationery',
    price: 799,
    compareAtPrice: 1199,
    stock: 140,
    rating: { average: 4.6, count: 512 },
    sold: 940,
    tags: ['stationery', 'planner', 'productivity'],
    description:
      'Undated so you can start any Monday — weekly spreads, monthly reviews, a habit grid and a project log in one spiral-bound book.',
    highlights: ['Undated — start anytime', 'Habit tracker grid', 'Spiral bound, lies flat'],
    specs: [
      { key: 'Size', value: 'A5' },
      { key: 'Pages', value: '210' },
      { key: 'Binding', value: 'Spiral' },
    ],
  },
];

export const coupons = [
  {
    code: 'MERIDIAN10',
    description: '10% off your order (max ₹500)',
    type: 'percent',
    value: 10,
    minOrder: 999,
    maxDiscount: 500,
  },
  {
    code: 'FIRST200',
    description: '₹200 off on orders above ₹1,499',
    type: 'fixed',
    value: 200,
    minOrder: 1499,
  },
  {
    code: 'FREESHIP',
    description: 'Free shipping on any order',
    type: 'shipping',
    value: 0,
    minOrder: 0,
  },
  {
    code: 'WELCOME5',
    description: '5% off for new customers',
    type: 'percent',
    value: 5,
    minOrder: 499,
    maxDiscount: 250,
  },
];
